[package]
name = "sharedaxi"
version = "0.1.0"
edition = "2021"

[dependencies]
aeon.workspace = true

anyhow.workspace = true
clap.workspace = true
log.workspace = true
serde.workspace = true
toml.workspace = true
