name = "brill"
output_dir = "output/idgen"
logging_level = 4
order = 4

[domain]
radius = 48.0
height = 48.0

[domain.cell]
subdivisions = 6
padding = 3

[domain.mesh]
refine_global = 1
max_level = 15

[solver]
max_steps = 100000
cfl = 0.5
dampening = 0.4
tolerance = 1e-6

[[instance]]
type = "brill"
suffix = "_1.0"
amplitude = 1.0
sigma = [1.0, 1.0]
