name = "brill"
output_dir = "output/idaxi"
order = 4

visualize_levels = true
visualize_result = true

max_error = 1e-6
max_level = 15
max_nodes = 16000000

[logging]
level = 5

[domain]
radius = 48.0
height = 48.0

[domain.cell]
subdivisions = 6
padding = 3

[domain.mesh]
refine_global = 1
max_level = 15

[solver]
max_steps = 100000
cfl = 0.5
dampening = 0.4
tolerance = 1e-6

[[source]]
type = "brill"
amplitude = 1.0
sigma = [1.0, 1.0]
