# Workspace configuration
[workspace]
members = ["crates/*", "tools/idbrill", "tools/evbrill"]
default-members = [
    "crates/aeon_basis",
    "crates/aeon_geometry",
    "tools/idbrill",
    "tools/evbrill",
    ".",
]
resolver = "2"

[workspace.dependencies]
aeon_array = { path = "crates/aeon_array" }
aeon_basis = { path = "crates/aeon_basis" }
aeon_geometry = { path = "crates/aeon_geometry" }
aeon_macros = { path = "crates/aeon_macros" }
aeon_tensor = { path = "crates/aeon_tensor" }

bitvec = { version = "1.0.1", features = ["serde"] }
bumpalo = "3.16.0"
cc = "1.0"
clap = "4.5.4"
env_logger = "0.11"
faer = "0.19.3"
itertools = "0.13.0"
log = "0.4"
paste = "1.0.15"
rand = "0.8.5"
rayon = "1.10.0"
reborrow = "0.5.5"
ron = "0.8"
serde = { version = "1.0.200", features = ["derive"] }
thread_local = "1.1.8"


# Main package (`aeon`) configuration.
[package]
name = "aeon"
version = "0.1.0"
edition = "2021"
exclude = ["crates/", "tools/"]
readme = "README.md"

[dependencies]
aeon_array.workspace = true
aeon_basis.workspace = true
aeon_geometry.workspace = true
aeon_macros.workspace = true

bitvec.workspace = true
bumpalo.workspace = true
log.workspace = true
rayon.workspace = true
reborrow.workspace = true
ron.workspace = true
serde.workspace = true
thread_local.workspace = true
vtkio = "0.6"

[dev-dependencies]
env_logger.workspace = true


[[example]]
name = "wamr"
path = "examples/wamr.rs"
