[package]
name = "aeon"
version = "0.1.0"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"

[[example]]
name = "poisson"
path = "examples/poisson.rs"
