[package]
name = "aeon"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[workspace]

members = ["crates/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aeon_macros = { path = "crates/aeon_macros" }

bumpalo = { version = "3" }

[dev-dependencies]

[[example]]
name = "evolution"
path = "examples/evolution.rs"
