# Workspace configuration
[workspace]
members = ["crates/*", "tools/idbrill", "tools/evbrill"]
resolver = "2"

[workspace.dependencies]
bitvec = { version = "1.0.1", features = ["serde"] }
cc = "1.0"
clap = "4.5.4"
env_logger = "0.11"
itertools = "0.13.0"
log = "0.4"
paste = "1.0.15"
rand = "0.8.5"
rayon = "1.10.0"
reborrow = "0.5.5"
ron = "0.8"

aeon_macros = { path = "crates/aeon_macros" }
aeon_tensor = { path = "crates/aeon_tensor" }


# Main package (`aeon`) configuration.
[package]
name = "aeon"
version = "0.1.0"
edition = "2021"
exclude = ["crates/", "tools/"]
readme = "README.md"

[dependencies]
aeon_macros.workspace = true

bitvec.workspace = true
log.workspace = true
rayon.workspace = true
reborrow.workspace = true
ron.workspace = true

serde = "1.0.200"
vtkio = "0.6"
