[package]
name = "aeon"
version = "0.1.0"
edition = "2021"
exclude = ["crates/"]
readme = "README.md"

[workspace]

members = ["crates/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aeon_macros = { path = "crates/aeon_macros" }
aeon_axisymmetry = { path = "crates/aeon_axisymmetry" }

bumpalo = "3"
log = "0.4"
serde = "1.0.200"
vtkio = "0.6"

[dev-dependencies]
clap = "4.5.4"
env_logger = "0.11"
ron = "0.8"

[[example]]
name = "idbrill"
path = "examples/idbrill.rs"


[[example]]
name = "evbrill"
path = "examples/evbrill.rs"
