[package]
name = "aeon"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[workspace]

members = ["crates/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aeon_macros = { path = "crates/aeon_macros" }

bumpalo = { version = "3" }
vtkio = { version = "0.6.3" }

[dev-dependencies]
soa_derive = "0.13"

[[example]]
name = "evolution"
path = "examples/evolution/main.rs"

[[example]]
name = "poisson"
path = "examples/poisson.rs"
