# Workspace configuration
[workspace]
members = [
    "crates/*",

    "tools/critaxi",
    "tools/sharedaxi",
    "tools/idaxi",
    "tools/evaxi",

    "tools/evsphere",
]
default-members = [
    "crates/aeon_geometry",

    "tools/critaxi",
    "tools/evaxi",
    "tools/idaxi",
    "tools/sharedaxi",

    "tools/evsphere",
    ".",
]
resolver = "2"

[workspace.dependencies]
aeon = { path = "." }
aeon_array = { path = "crates/aeon_array" }
aeon_geometry = { path = "crates/aeon_geometry" }
aeon_macros = { path = "crates/aeon_macros" }
aeon_tensor = { path = "crates/aeon_tensor" }

sharedaxi = { path = "tools/sharedaxi" }

anyhow = "1.0.91"
bitvec = { version = "1.0.1", features = ["serde"] }
bumpalo = "3.16.0"
cc = "1.0"
clap = "4.5.4"
env_logger = "0.11"
faer = "0.20.1"
itertools = "0.13.0"
log = "0.4"
num-traits = "0.2.19"
paste = "1.0.15"
rand = "0.8.5"
rayon = "1.10.0"
reborrow = "0.5.5"
ron = "0.8"
serde = { version = "1.0.200", features = ["derive"] }
thiserror = "2.0.9"
thread_local = "1.1.8"
toml = "0.8.19"

# Main package (`aeon`) configuration.
[package]
name = "aeon"
version = "0.1.0"
edition = "2021"
exclude = ["crates/", "tools/"]
readme = "README.md"

[dependencies]
aeon_array.workspace = true
aeon_geometry.workspace = true
aeon_macros.workspace = true

bitvec.workspace = true
bumpalo.workspace = true
faer.workspace = true
log.workspace = true
num-traits.workspace = true
rayon.workspace = true
reborrow.workspace = true
ron.workspace = true
serde.workspace = true
thiserror.workspace = true
thread_local.workspace = true
vtkio = "0.6"

[dev-dependencies]
env_logger.workspace = true
anyhow.workspace = true

[[example]]
name = "wamr"
path = "examples/wamr.rs"

[[example]]
name = "wave"
path = "examples/wave.rs"

[[example]]
name = "transfer"
path = "examples/transfer.rs"

[[example]]
name = "poisson"
path = "examples/poisson.rs"
