[workspace]
members = ["crates/*", "tools/idbrill", "tools/evbrill"]
resolver = "2"

[workspace.dependencies]
clap = "4.5.4"
env_logger = "0.11"
log = "0.4"
ron = "0.8"

[package]
name = "aeon"
version = "0.1.0"
edition = "2021"
exclude = ["crates/", "tools/"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aeon_macros = { path = "crates/aeon_macros" }
aeon_axisymmetry = { path = "crates/aeon_axisymmetry" }

log.workspace = true

bumpalo = "3"
serde = "1.0.200"
vtkio = "0.6"

[dev-dependencies]
clap = "4.5.4"
env_logger = "0.11"
ron = "0.8"
