[package]
name = "critaxi"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger.workspace = true
eyre.workspace = true
clap.workspace = true
log.workspace = true
reborrow.workspace = true
serde.workspace = true
sharedaxi.workspace = true
toml.workspace = true
