[package]
name = "critaxi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
env_logger = "0.11"
clap.workspace = true
log.workspace = true
reborrow.workspace = true
serde.workspace = true
sharedaxi.workspace = true
toml.workspace = true
