[package]
name = "asphere"
version = "0.1.0"
edition = "2024"

[dependencies]
aeon.workspace = true
aeon_config.workspace = true
clap.workspace = true
color-eyre.workspace = true
console.workspace = true
eyre.workspace = true
env_logger.workspace = true
log.workspace = true
reborrow.workspace = true
serde.workspace = true
toml.workspace = true
