[package]
name = "asphere"
version = "0.2.2"
edition = "2024"

[features]
default = ["progress"]
progress = []

[dependencies]
aeon.workspace = true
aeon_app.workspace = true
clap.workspace = true
color-eyre.workspace = true
console.workspace = true
circular-queue.workspace = true
csv.workspace = true
datasize.workspace = true
eyre.workspace = true
env_logger.workspace = true
indicatif.workspace = true
log.workspace = true
reborrow.workspace = true
serde.workspace = true
