name = "CodeGen"
uuid = "4368a3ab-6209-4b5f-89ab-6caaa6583ffe"
authors = ["lukazmm <lukas.m.mesicek@gmail.com>"]
version = "0.1.0"

[deps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
