name = "Analyze"
uuid = "63f6177f-2fff-4ee6-8cf4-8398f6a232a7"
authors = ["lukazmm <lukas.m.mesicek@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
Plots = "1.40.14"
TOML = "1.0.3"
