name = "brill"
output_dir = "output/brillcrit"
order = 4

start = 1.0
end = 4.0

cache_initial = true
cache_evolve = false

bifurcations = 2

[limits]
max_coord_time = 10.0
max_proper_time = 10.0
max_nodes = 10_000_000

[logging]
level = 5

[domain]
radius = 48.0
height = 48.0

[domain.cell]
subdivisions = 6
ghost = 3

[domain.mesh]
refine_global = 1
max_level = 15

[solver]
max_steps = 100000
cfl = 0.5
dampening = 0.4
tolerance = 1e-6
