name = "prolateid"
output_dir = "output/prolateid"
order = 4

visualize_levels = true
visualize_result = true
visualize_stride = 6

max_error = 1e-6
max_level = 15
max_nodes = 16_000_000
refine_global = 1

[logging]
level = 5

[domain]
radius = 48.0
height = 48.0

[domain.cell]
subdivisions = 6
padding = 3

[solver]
max_steps = 1000000
cfl = 0.5
dampening = 0.4
tolerance = 1e-6

[[source]]
type = "scalar_field"
mass = 0.0
amplitude = 2.5
sigma = [2.0, 1.0]
