name = "sphere"
output_dir = "output/spherecrit"
order = 4

start = 0.0
end = 2.0

cache_initial = true
cache_evolve = false

bifurcations = 2

[logging]
level = 5

[domain]
radius = 48.0
height = 48.0

[domain.cell]
subdivisions = 6
ghost = 3

[solver]
max_steps = 10_000_000
cfl = 0.5
dampening = 0.4
tolerance = 1e-6

[regrid]
coarsen_tolerance = 1e-8
refine_tolerance = 1e-6
flag_interval = 20
max_levels = 15

[limits]
max_coord_time = 100.0
max_proper_time = 10.0
max_nodes = 500_000
max_steps = 10_000_000
