directory = "output/sphgauss1/search"
parameter = "amplitude"
parallel = 9
start = 0.33603529                    # Disperses 
end = 0.33603530                      # Collapses
max_depth = 40
min_error = 1e-16
