name = "sphgauss1"
directory = "output/sphgauss1/${amplitude}"

[domain]
radius = 40.0

[limits]
max_levels = 24
max_nodes = 10_000_000
max_memory = 5_000_000_000

[evolve]
cfl = 0.3
dissipation = 0.5
max_proper_time = 6.4
max_steps = 10_000_000
max_constraint = 1.0
min_lapse = 0.0

[regrid]
coarsen_error = 1e-10
refine_error = 1e-8
global = 2
flag_interval = 20
fix_grid = false

[visualize]
save_initial = false
save_initial_levels = false
save_evolve = true
save_evolve_interval = 0.05
stride = "per_vertex"

[diagnostic]
save_evolve = false
save_evolve_interval = 20

[[sources]]
mass = 0.0
profile.type = "gaussian"
profile.amplitude = "${amplitude}"
profile.sigma = 5.35
profile.center = 0.0
