name = "sphgauss1"
directory = "output/sphgauss1/${amplitude}"

[domain]
radius = 40.0

[limits]
max_levels = 21
max_nodes = 10_000_000
max_memory = 5_000_000_000

[evolve]
cfl = 0.3
dissipation = 0.5
max_proper_time = 7.0
max_steps = 700_000

[regrid]
coarsen_error = 1e-10
refine_error = 1e-8
global = 2
flag_interval = 20

[visualize]
save_initial = false
save_initial_levels = false
save_evolve = false
save_evolve_interval = 0.05
stride = "per_vertex"

[diagnostic]
save = false
save_interval = 1
serial_id = 0

[[sources]]
mass = 0.0
profile.type = "gaussian"
profile.amplitude = "${amplitude}"
profile.sigma = 5.35
profile.center = 0.0
