# Config file compatible with Cole's code.

name = "sphgauss2-cole"
directory = "."

[domain]
radius = 40.0

[limits]
max_levels = 21
max_nodes = 10_000_000
max_memory = 5_000_000_000

[evolve]
cfl = 0.3
dissipation = 0.5
max_proper_time = 7.6
max_steps = 800_000

[regrid]
coarsen_error = 1e-10
refine_error = 1e-8
global = 2
flag_interval = 20

[visualize]
save_initial = false
save_initial_levels = false
save_evolve = false
save_evolve_interval = 0.05
stride = "per_vertex"

[diagnostic]
save = true
save_interval = 1
serial_id = "$1"

[[sources]]
mass = 0.0
profile.type = "gaussian"
profile.amplitude = "$0"
profile.sigma = 1.0
profile.center = 3.0
