name = "sphgauss1"
directory = "output/sphgauss1/${amplitude}"

[execution]
mode = "search"
directory = "output/sphgauss1/search"
parameter = "amplitude"
start = 0.3360352955
end = 0.3360352956
max_depth = 20
min_error = 1e-14

[domain]
radius = 40.0

[limits]
max_levels = 24
max_nodes = 10_000_000
max_memory = 5_000_000_000

[evolve]
cfl = 0.3
dissipation = 0.5
max_proper_time = 7.6
max_steps = 10_000_000

[regrid]
coarsen_error = 1e-10
refine_error = 1e-8
global = 2
flag_interval = 20

[visualize]
save_initial = false
save_initial_levels = false
save_evolve = false
save_evolve_interval = 0.2
stride = "per_vertex"

[diagnostic]
save = false
save_interval = 1
serial_id = 0

[[sources]]
mass = 0.0
profile.type = "gaussian"
profile.amplitude = "${amplitude}"
profile.sigma = 5.35
profile.center = 0.0
