directory = "output/sphtanh/search"
parameter = "amplitude"
start = 0.05                        # Disperses 
end = 0.10                          # Collapses
max_depth = 100
min_error = 1e-16
parallel = 9
# Critical Search result 0.09545428876233998
