# Spherical scalar configuration file using hyperbolic tangent initial profile.
name = "sphtanh"
directory = "output/sphtanh/${amplitude}"

[domain]
radius = 40.0

[limits]
max_levels = 19
max_nodes = 10_000_000
max_memory = 5_000_000_000

[evolve]
cfl = 0.3
dissipation = 0.5
max_proper_time = 5.0
max_steps = 2_000_000
max_constraint = 1.0
min_lapse = 1e-8

[regrid]
coarsen_error = 1e-10
refine_error = 1e-8
global = 2
flag_interval = 20

[visualize]
save_initial = false
save_initial_levels = false
save_evolve = false
save_evolve_interval = 0.01
stride = "per_vertex"

[[sources]]
mass = 0.0
profile.type = "tanh"
profile.amplitude = "${amplitude}"
profile.sigma = 1.0
profile.center = 3.0
smooth.strength = 0.001
smooth.power = 1.4
