[package]
name = "aeon_app"
version = "0.3.1"
edition = "2021"

[dependencies]
bincode.workspace = true
clap.workspace = true
chumsky.workspace = true
indicatif.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
rand.workspace = true
