[package]
name = "aaxi"
version = "0.1.0"
edition = "2024"

[dependencies]
aeon.workspace = true
aeon_tensor.workspace = true
clap.workspace = true
color-eyre.workspace = true
console.workspace = true
datasize.workspace = true
eyre.workspace = true
indicatif.workspace = true
log.workspace = true
reborrow.workspace = true
serde.workspace = true
toml.workspace = true
