[package]
name = "idaxi"
version = "0.1.0"
edition = "2021"

[dependencies]
aeon.workspace = true

anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
reborrow.workspace = true
serde.workspace = true
sharedaxi.workspace = true
